spring.application.name=eletronico
spring.datasource.url=jdbc:mysql://localhost:3306/ponto_eletronico
spring.datasource.username=springuser
spring.datasource.password=93145318

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
